# Generated by Django 4.1 on 2022-08-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('overall', models.FloatField(default=0.0)),
                ('easy', models.FloatField(default=0.0)),
                ('knowledge', models.FloatField(default=0.0)),
                ('fun', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='fun',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='overall',
        ),
    ]
