# Generated by Django 4.1 on 2022-08-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('prof', models.CharField(default=None, max_length=40)),
                ('easy', models.FloatField(default=0.0)),
                ('knowledge', models.FloatField(default=0.0)),
                ('fun', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='fun',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='overall',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=555),
        ),
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('ects', models.IntegerField()),
                ('school', models.CharField(max_length=555)),
                ('department', models.CharField(max_length=555)),
                ('description', models.TextField()),
                ('prereq', models.CharField(max_length=555)),
                ('coreq', models.CharField(max_length=555)),
                ('antireq', models.CharField(max_length=555)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.course')),
            ],
        ),
    ]
