# Generated by Django 4.1 on 2022-08-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_comment_remove_professor_easy_remove_professor_fun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='prof',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
