# Generated by Django 4.1 on 2022-08-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_comment_remove_professor_easy_remove_professor_fun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='prof',
            field=models.CharField(default=None, max_length=555),
        ),
    ]
