# Generated by Django 4.1 on 2022-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_comment_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='prof',
            field=models.CharField(default=None, max_length=5550),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=5550),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='antireq',
            field=models.CharField(max_length=55500),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='coreq',
            field=models.CharField(max_length=55500),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='department',
            field=models.CharField(max_length=55500),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='prereq',
            field=models.CharField(max_length=55500),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='school',
            field=models.CharField(max_length=55500),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='title',
            field=models.CharField(max_length=55500),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=5550),
        ),
    ]
