# Generated by Django 4.1 on 2022-08-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_comment_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='overall',
        ),
    ]
