# Generated by Django 4.1 on 2022-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_comment_prof_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_rating',
            field=models.IntegerField(default=0),
        ),
    ]
