# Generated by Django 4.1 on 2022-08-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcode',
            name='change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='contests_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='img_url',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='top_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leetcode',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
